### ISSUE TITLE
Remove the obsoleted parts

### ISSUE THREAD

**Issue by xuzhen** [M7S/dockbarx#105]
the obsoleted parts:
[Avant Window Navigator](https://github.com/p12tic/awn) applet: 2 years inactive, still python2/gtk2
[DockManager](https://launchpad.net/dockmanager) related things: DockManager was dead long long ago
GNOME panel applet: no longer work with GNOME 3

We should remove those code, at least in the python3 branch.

**Comment by M7S** [comment]
I agree.

**Comment by xuzhen** [comment]
I also removed the [Cardapio](https://launchpad.net/cardapio) and [Namebar](https://launchpad.net/namebar) applet in pull request #106

**Comment by M7S** [comment]
Thank you!
