### ISSUE TITLE
zg.py needs to be rewritten

### ISSUE THREAD

**Issue by xuzhen** [M7S/dockbarx#107]
from https://github.com/M7S/dockbarx/blob/pygi-python3/dockbarx/zg.py#L29
`from zeitgeist import client, datamodel`

The problem is that there is no python3-zeitgeist on Ubuntu.
python3-zeitgeist on Debian is [not compatible with python3](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=943994), and the maintainer suggests using GIR binding instead.

**Comment by M7S** [comment]
Fixed.
