### ISSUE TITLE
Mouse button options don't seem to take effect

### ISSUE THREAD

**Issue by lowercasename** [M7S/dockbarx#121]
Hi, thank you so much for DockBarX, it's really great! My only issue at the moment is that I've set the option to 'middle click' under 'Window Item' in the preferences to 'no action', but it's still closing windows on middle click. Setting any of the options seems to have no effect on what actually happens when I click on windows - whatever the left mouse button is set to, for instance, it will always select or minimise.

**Comment by xuzhen** [comment]
I can't reproduce this on my system, neither with gtk2 nor gtk3 version. What's your Linux distribution and Dockbarx version?

**Comment by lowercasename** [comment]
DockBarX 0.93, compiled from source, Fedora 31. I'm running it in the XFCE panel plugin, but I just checked the standalone app and it also closes windows on middle click (I've currently got the setting as 'show menu'). Other settings seem to take effect just fine!

**Comment by lowercasename** [comment]
Mysteriously, the click settings appear to have started working now! I think this can be closed since you can't replicate it, and I'll reopen it if the problem comes back.
