### ISSUE TITLE
Custom launchers in DockBarX

### ISSUE THREAD

**Issue by notsatvrn** [M7S/dockbarx#123]
Hi. I am having an issue with multiple apps where the launchers open a window that can't be pinned because it has no launcher file. Is there a folder where I can put the launchers into and have them automatically pinned? Or is there a config file where I can change this? I haven't been able to find any config files with mlocate.

Thank you in advance.

UPDATE: I built the latest version just to be sure, and when running and looking at the output, clicking 'Edit custom launcher' returns this:
`Error: Found no program for editing .desktop files.`

**Comment by xuzhen** [comment]
The 'Edit custom launcher' feature support the following editors only: gnome-desktop-item-edit (was from gnome-panel),  mate-desktop-item-edit (from mate-panel), exo-desktop-item-edit (from exo-utils)

And it's possible to add pinned launchers manually.

If you are using the 0.93 version of dockbarx (python2/gtk2), run gconf-editor and edit /apps/dockbarx/launchers
If you are using the 1.0 beta version of dockbarx (python3/gtk3), run dconf-editor and edit /org/dockbarx/dockbarx/launchers

Set the value to
```['NAME;PATH-OF-DESKTOP-FILE', ...]```

You could put your .desktop file into ~/.local/share/dockbarx/launchers
```['abc;/home/user/.local/share/dockbarx/launchers/abc.desktop']```

**Comment by notsatvrn** [comment]
Thank you @xuzhen 

EDIT: Installing exo fixed the issue.
