### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by philipzae** [M7S/dockbarx#125]
If dockbarx is to have a chance to get into Debian and other distros, it would need to be upgraded to python 3, as python 2 is being deprecated everywhere.

**Comment by xuzhen** [comment]
Here is the python3 branch: https://github.com/M7S/dockbarx/tree/pygi-python3

**Comment by philipzae** [comment]
Is it fully functional and can a build be created for it.

**Comment by xuzhen** [comment]
The packages in my PPA for Ubuntu 20.04 were built from that branch https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx?field.series_filter=focal

**Comment by philipzae** [comment]
That's great. I would like dockbarx to become more popular by getting it into the debian and ubuntu repositories and hopefully used by default in more distros, so it would be great if you could assist with this effort in issue #92.
