### ISSUE TITLE
 Window class don't match on DockbarX

### ISSUE THREAD

**Issue by rauldipeas** [M7S/dockbarx#127]
When i launch a webpin app that ain't pin on panel, it doesn't show app icon on DockbarX.

![ksnip_20200604-161436](https://user-images.githubusercontent.com/12108031/83800956-aaceef80-a67e-11ea-9ee5-0a35841f4dd3.png)

**Comment by xuzhen** [comment]
Fixed in the gtk3/python3 branch. The new packages for ubuntu 20.04 has been uploaded to my PPA.

**Comment by rauldipeas** [comment]
Perfect! Thank you so much!
![ksnip_20200608-163816](https://user-images.githubusercontent.com/12108031/84073065-82106800-a9a6-11ea-96ed-16845120be00.png)
