### ISSUE TITLE
xfce4-dockbarx-plugin missing from PPA for Eoan

### ISSUE THREAD

**Issue by philipzae** [M7S/dockbarx#129]
Was trying to install the xfce plugin for dockbarx on Xubuntu 19.10 but the PPA doesn't have it.

![image](https://user-images.githubusercontent.com/4412114/85626468-26b8c800-b67e-11ea-9709-1acd29754f90.png)

![image](https://user-images.githubusercontent.com/4412114/85626626-5ec00b00-b67e-11ea-909b-5176284ad069.png)

**Comment by xuzhen** [comment]
Sorry for the inconvenience. I've uploaded the package for 19.10.

**Comment by philipzae** [comment]
Thank you very much.

Please be of notice that DockbarX will be features in Xubuntu's revamped documentation, which we hope to release with 20.10.
