### ISSUE TITLE
gnomepanel-applet-dockbarx broken since Ubuntu 13.04/Linux Mint 15

### ISSUE THREAD

**Issue by tponthieux** [M7S/dockbarx#13]
DockBarX cannot be used as a gnome panel applet in Linux Mint 17 MATE  (Ubuntu 14.04). This is such an important feature I'm considering going back to Mint 14.

```
gnomepanel-applet-dockbarx:
 Depends: python-gnomeapplet  but it is not installable
```

http://www.techsupportalert.com/content/tips-and-tricks-linux-mint-after-installation-mint-13-maya-mate-edition.htm
"Note: The DockBarX applet didn't work with the MATE version for Linux Mint 15 and 16 at time of checking."

**Comment by Isakku** [comment]
Having the same problem here. I'm wondering if it could be possible to redo that part of the code without using that pesky python-gnomeapplet. As far as I have messed with this, I would need to download linux mint 14 to be able to use this. what a disappointment!
