### ISSUE TITLE
Dockbarx-plugin: Have larger launcher icons

### ISSUE THREAD

**Issue by philipzae** [M7S/dockbarx#131]
With a 32px panel height, standard launcher icons appear as 24px, while dockbarx launcher icons appear at 20px.

![image](https://user-images.githubusercontent.com/4412114/85871430-74007b00-b7df-11ea-9307-4434dd02c4b2.png)

**Comment by rauldipeas** [comment]
You could change theme, or edit the stock ones.

**Comment by philipzae** [comment]
Changing the theme doesn't change the smaller icons appearing in dockbarx.

**Comment by rauldipeas** [comment]
Every theme has a different icon size.

**Comment by philipzae** [comment]
All themes have standard icon sizes of 16, 22, 24, 48, etc. Some themes may have a square or circle shape within the icons, but this doesn't change the size of the icons. I'm requesting that dockboarx's algo to determine the size of the rendered icons be updated.

**Comment by xuzhen** [comment]
It's written in dockbarx's theme configuration.
Here is a code snippet form Glassified theme
```
		<pixmap name="bg_icon">
			<get_icon size="-8" />
			<correct_size />
			<if type="some_minimized">
				<transp_sat opacity="60" saturation="0" />
			</if>
			<if type="!some_minimized">
				<pixmap_from_self name="black_icon">
					<colorize color="#000000" />
				</pixmap_from_self>
				<composite bg="self" fg="black_icon" opacity="30" />
			</if>
		</pixmap>
		<composite bg="empty" fg="bg_icon" opacity="100" xoffset="-4" yoffset="-4" />
		<pixmap name="fg_icon">
			<get_icon size="-8" />
			<correct_size />
			
		</pixmap>
		<composite bg="self" fg="fg_icon" opacity="100" xoffset="2" yoffset="1" />

```
For the default Glassified theme, the icon size will be the "available" height minus 8px.

**Comment by philipzae** [comment]
@rauldipeas Sorry I see that we were talking about two different themes. I was talking about the system's icon theme and you were referring to the dockbarx theme. :D

**Comment by Golddouble** [comment]
Not sure how to get bigger icons.

I have replaced two times
`<get_icon size="-8" />`
through
`<get_icon size="-0" />`

Has no effect.

**Comment by xuzhen** [comment]
@Golddouble there are also some ```<shrink percent="XX" />``` commands. You need to change those values too.
