### ISSUE TITLE
Desktop Action not showing

### ISSUE THREAD

**Issue by cbruno1** [M7S/dockbarx#134]
In the screenshot I have attached, you may not see the two desired actions in the dock.

Sample usr/share/applications/firefox.desktop :

```
[Desktop Action new-window]
Name=Open a New Window
Exec=firefox -new-window

[Desktop Action new-private-window]
Name=Open a New Private Window
Exec=firefox -private-window
```

Is this a bug?

Thank you in advance.

![exp 1](https://user-images.githubusercontent.com/67806509/86497695-ec88ae00-bd82-11ea-90de-802d41673013.png)

**Comment by xuzhen** [comment]
I can't reproduce this issue on my system. What's your Linux distribution? And where does the dockbarx package on your system come from? Is there any errors in ~/.local/share/dockbarx/log/dockbarx.log?

**Comment by cbruno1** [comment]
Thank you for your reply.

> I can't reproduce this issue on my system. What's your Linux distribution? 

I am using Xubuntu 20.04, my desktop environement is XFCE.

>  And where does the dockbarx package on your system come from?

https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx

```
$ apt info dockbarx
Package: dockbarx
Version: 1.0~beta+git20200608-1~ppa1
```
```
$ apt info xfce4-dockbarx-plugin
Package: xfce4-dockbarx-plugin
Version: 0.6-1~focal1
```
> Is there any errors in ~/.local/share/dockbarx/log/dockbarx.log?

no error message :-/

```
$ cat ~/.local/share/dockbarx/log/dockbarx.log
INFO	| 2020-07-03 22:28:20,349	| DockbarX 1.0-beta
INFO	| 2020-07-03 22:28:20,350	| DockbarX init
INFO	| 2020-07-03 22:28:20,421	| DockbarX reload
```
same result by launching dockx from the shell.

I uninstalled and reinstalled dockbarx, but I couldn't delete my personal configuration:
```
rm -rf ~/.local/share/dockbarx/
```
Was not enough.

**Comment by cbruno1** [comment]
I solved problem. Activate option _use the static quick lists of unity_,in preferences panel the plugins section.
