### ISSUE TITLE
Disabling "Reorder window list" isn't working.

### ISSUE THREAD

**Issue by ahmubashshir** [M7S/dockbarx#135]
I Have disabled "Reorder the window list...", but window list is being reordered...
![image](https://user-images.githubusercontent.com/24864366/87086477-79d07480-c253-11ea-8d6d-4e0d31d2149c.png)
![image](https://user-images.githubusercontent.com/24864366/87086516-85bc3680-c253-11ea-9c23-1405d3b16a39.png)

![image](https://user-images.githubusercontent.com/24864366/87086272-2c540780-c253-11ea-9c39-d9217e714fae.png)

**Comment by xuzhen** [comment]
Can you install dconf-cli and tell me the result of ```dconf read /org/dockbarx/dockbarx/reorder-window-list``` ?

**Comment by ahmubashshir** [comment]
> Can you install dconf-cli and tell me the result of `dconf read /org/dockbarx/dockbarx/reorder-window-list` ?

It returns nothing.

**Comment by ahmubashshir** [comment]
After I ran `dconf write /org/dockbarx/dockbarx/reorder-window-list false`, it started working... Should I Close this issue now?

**Comment by xuzhen** [comment]
This is a checked state displaying bug which has been fixed in the pull request #136.
