### ISSUE TITLE
Xfce panel plugin solid color not working as it should

### ISSUE THREAD

**Issue by philipzae** [M7S/dockbarx#137]
If I set the panel plugin to have a solid color and set the alpha value other an 100%, the blending between the solid color and the background color of the panel isn't correct.
![image](https://user-images.githubusercontent.com/4412114/87241027-edc77400-c42f-11ea-8db3-32cec9c0011b.png)

**Comment by xuzhen** [comment]
The xfce4-dockbarx-plugin is a separate project, please report bugs there https://github.com/M7S/xfce4-dockbarx-plugin/issues

**Comment by philipzae** [comment]
Thanks. Filed there. https://github.com/M7S/xfce4-dockbarx-plugin/issues/4
