### ISSUE TITLE
Enable recent files context menu

### ISSUE THREAD

**Issue by cbruno1** [M7S/dockbarx#139]
I just made a new Xubuntu installation. On a previous installation, when I right clicked on my text editor on my video player, a list of recent files was displayed. On my new installation, this list is no longer displayed. 
Here is some information:

```
$ cat ~/.local/share/dockbarx/log/dockbarx.log
INFO	| 2020-07-27 11:15:53,336	| DockbarX 1.0-beta
INFO	| 2020-07-27 11:15:53,337	| DockbarX init
INFO	| 2020-07-27 11:15:53,406	| DockbarX reload
INFO	| 2020-07-27 11:16:22,401	| Executing: mousepad 
INFO	| 2020-07-27 11:16:40,841	| Executing: celluloid 
INFO	| 2020-07-27 11:19:05,051	| Executing: mousepad
``` 

```
$ apt info xfce4-dockbarx-plugin
Package: xfce4-dockbarx-plugin
Version: 0.6+git20200718-1~ppa1~20.04
Priority: optional
Section: xfce
Maintainer: Xu Zhen <xuzhen@fastmail.com>
Installed-Size: 121 kB
Depends: libc6 (>= 2.4), libglib2.0-0 (>= 2.42), libgtk-3-0 (>= 3.22), libxfce4panel-2.0-4 (>= 4.11.0), libxfconf-0-3 (>= 4.6.0), dockbarx-common (>= 1.0~beta)
Download-Size: 48,3 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/xuzhen666/dockbarx/ubuntu focal/main amd64 Packages
Description: DockBarX plugin for Xfce
 This is a DockBarX plugin for the Xfce panel
```

**Comment by xuzhen** [comment]
``` sudo apt install zeitgeist gir1.2-zeitgeist-2.0```, that menu will come back.
I moved those packages from ```Recommends``` into ```Suggests``` of the dockbarx-common package, therefore they will not be installed by default.

**Comment by cbruno1** [comment]
Thanks Xuzhen, work perfectly!

![Capture d’écran_2020-07-27_14-26-49](https://user-images.githubusercontent.com/67806509/88541620-5e1beb00-d015-11ea-8644-62740f8ab509.png)
