### ISSUE TITLE
Window Previews do not work

### ISSUE THREAD

**Issue by tponthieux** [M7S/dockbarx#14]
The instructions to enable window previews are either obsolete or inadequate for Linux Mint 17 MATE/Ubuntu 14.04. I actually haven't had this working since Ubuntu 10.04, but a note in the README.md file leads me to believe it should be possible.

"NOTE! To use previews with Compiz you need to activate KDE Compability in compiz settings manager and under KDE Compability check "Support Plasma Thumbnails". You can *not** use previews with other window manager than Compiz and Kwin."

The following did not enable window previews:
- checked KDE Compatability in compiz settings
- verified "Support Plasma Thumnails" was checked
- checked CompizConfig Settings Manager > Extras > Thumbnail Window Previews
- checked DockBarX Preferences > Window List > Previews > Show previews
- checked DockBarX Preferences > Window List > Previews > Show previews for minimized windows

How can I get thumbnail window previews to work?

**Comment by xuzhen** [comment]
window preview only works on plasma desktop.

**Comment by aikeru** [comment]
This solved it for me:
http://askubuntu.com/questions/17290/window-preview-is-not-working-in-dockbarx

**Comment by tponthieux** [comment]
@aikeru what distro and version of Linux are you using?

**Comment by aikeru** [comment]
Ubuntu 14.04 with binary proprietary nvidia drivers.
