### ISSUE TITLE
Dockbarx doesn't work with x2go since gtk3 migration

### ISSUE THREAD

**Issue by elgabo86** [M7S/dockbarx#143]
Using xfce through x2go, dockbarx doesn't work since the gtk3 migration. But it works if i start a local session.

Here is the log :

INFO	| 2020-08-12 11:21:41,276	| DockbarX 1.0-beta
INFO	| 2020-08-12 11:21:41,276	| DockbarX init
INFO	| 2020-08-12 11:21:41,337	| DockbarX reload
ERROR	| 2020-08-12 11:21:41,383	| Traceback (most recent call last):
ERROR	| 2020-08-12 11:21:41,383	|   File "/usr/bin/dockx", line 1533, in <module>
ERROR	| 2020-08-12 11:21:41,384	|     dockx = DockX(monitor)
ERROR	| 2020-08-12 11:21:41,384	|   File "/usr/bin/dockx", line 519, in __init__
ERROR	| 2020-08-12 11:21:41,384	|     self.dockbar.load()
ERROR	| 2020-08-12 11:21:41,384	|   File "/usr/lib/python3.8/site-packages/dockbarx/dockbar.py", line 536, in load
ERROR	| 2020-08-12 11:21:41,384	|     self.reload(tell_parent=False)
ERROR	| 2020-08-12 11:21:41,384	|   File "/usr/lib/python3.8/site-packages/dockbarx/dockbar.py", line 611, in reload
ERROR	| 2020-08-12 11:21:41,384	|     self.__on_window_opened(self.screen, window)
ERROR	| 2020-08-12 11:21:41,384	|   File "/usr/lib/python3.8/site-packages/dockbarx/dockbar.py", line 859, in __on_window_opened
ERROR	| 2020-08-12 11:21:41,385	|     self.__add_window(window)
ERROR	| 2020-08-12 11:21:41,385	|   File "/usr/lib/python3.8/site-packages/dockbarx/dockbar.py", line 1045, in __add_window
ERROR	| 2020-08-12 11:21:41,385	|     group = self.__make_groupbutton(identifier=identifier,
ERROR	| 2020-08-12 11:21:41,385	|   File "/usr/lib/python3.8/site-packages/dockbarx/dockbar.py", line 935, in __make_groupbutton
ERROR	| 2020-08-12 11:21:41,385	|     group = Group(self, identifier, desktop_entry, pinned, self.size)
ERROR	| 2020-08-12 11:21:41,385	|   File "/usr/lib/python3.8/site-packages/dockbarx/groupbutton.py", line 181, in __init__
ERROR	| 2020-08-12 11:21:41,385	|     self.popup = GroupPopup(self)
ERROR	| 2020-08-12 11:21:41,385	|   File "/usr/lib/python3.8/site-packages/dockbarx/groupbutton.py", line 2011, in __init__
ERROR	| 2020-08-12 11:21:41,386	|     CairoPopup.__init__(self, self.dockbar_r().orient, no_arrow, type_)
ERROR	| 2020-08-12 11:21:41,386	|   File "/usr/lib/python3.8/site-packages/dockbarx/cairowidgets.py", line 490, in __init__
ERROR	| 2020-08-12 11:21:41,386	|     visual = gdk_screen.get_rgb_visual()
ERROR	| 2020-08-12 11:21:41,386	| AttributeError: 'X11Screen' object has no attribute 'get_rgb_visual'

Thanks for your project !

**Comment by xuzhen** [comment]
Fixed in https://github.com/xuzhen/dockbarx/commit/8d5bf59e35381f8350b09443324f577402e4f858, waiting for #142 to be merged

**Comment by elgabo86** [comment]
It works, thanks!
