### ISSUE TITLE
pygi-python3: Screen space not initially reserved

### ISSUE THREAD

**Issue by tycho-kirchner** [M7S/dockbarx#144]
Hi and thanks for this project,
It seems that [#142](https://github.com/M7S/dockbarx/pull/142) which fixes [#140 ](https://github.com/M7S/dockbarx/issues/140) also needs to be applied to the pygi-python3-branch (1.0-beta).

Thanks
Tycho

**Comment by xuzhen** [comment]
That pull request IS made for the pygi-python3 branch.

**Comment by tycho-kirchner** [comment]
Ups - sorry. Don't know what i have seen yesterday...
