### ISSUE TITLE
Workaround for gnome-desktop-item-edit removal

### ISSUE THREAD

**Issue by nmsutton** [M7S/dockbarx#146]
Dockbarx relies on the program gnome-desktop-item-edit to create custom program launcher shortcuts, but unfortunately this has been removed from Ubuntu starting with 19.10. I found a workaround for this. Put the program from an older version of Ubuntu into /usr/bin/ and it works again, including with DockbarX. Here is a copy of the program I used ([download link](https://github.com/M7S/dockbarx/files/5113330/gnome-desktop-item-edit.zip)) from Ubuntu 18.10. Perhaps this could be included in future DockbarX releases, since I assume it is kind of abandon in development now, but can retain this useful part of DockbarX functionality. I don't know what the open source licence is on it, but it is probably similar to Ubuntu's licence. If the Ubuntu devs in the future write a new program to add this functionality back into the OS, then that could be added to DockbarX, but for now this may be the option available. I also opened up a [form post](https://askubuntu.com/questions/1264331/why-was-gnome-desktop-item-edit-removed) about the removal of the program.

**Comment by xuzhen** [comment]
I wrote a simple editor. It will be used when no {gnome,mate,exo}-desktop-item-edit installed

**Comment by nmsutton** [comment]
@xuzhen thanks! Good to know the create launcher ability will continue to work even in the case that Ubuntu has an issue with that.
