### ISSUE TITLE
pygi-python3 "preview-minimized" is not implemented

### ISSUE THREAD

**Issue by trappedinspacetime** [M7S/dockbarx#149]
I am on Ubuntu 20.04 `mate desktop`  platform. Compiz dropped `KDE compatibility` plugin. However, I created a [patch](https://gist.github.com/trappedinspacetime/cbeac325981527cedb01cda2e1a559b9#file-kdecompat-patch) and restored that plugin. But I noticed that pygi-python3 `preview-minimized` has been not implemented yet: https://github.com/M7S/dockbarx/blob/pygi-python3/dockbarx/windowbutton.py#L515

How can I implement that functionality?

**Comment by xuzhen** [comment]
The old code was removed by commit https://github.com/M7S/dockbarx/commit/0ab5a0233ad556e2f083f0f3ef253216f511cd58
You could add it back, but it may conflict with the current preview implementation.

**Comment by trappedinspacetime** [comment]
@xuzhen Thank you for responding. Your tip worked. I created [this](https://gist.github.com/trappedinspacetime/20586e0f4fe7620c58c8e4cb0f9d7770) patch from the commit you posted and reverted the commit, It does what I want now. But it  overlays the icon of the application in the minimized window preview. I should remove it. 
Another issue, I  know that live preview is not supported in the browsers. Is there anything I can do with it?

**Comment by xuzhen** [comment]
> it overlays the icon of the application in the minimized window preview. I should remove it.

Replace [this line](https://github.com/M7S/dockbarx/blob/pygi-python3/dockbarx/windowbutton.py#L513) with a ```return```

>  Another issue, I know that live preview is not supported in the browsers. Is there anything I can do with it?

I've no idea.

**Comment by trappedinspacetime** [comment]
@xuzhen Thank you again for your help. 
I have a question, `live thumbnail preview` looks dark. How can I make it luminous?
Regards.

**Comment by trappedinspacetime** [comment]
> I have a question, live thumbnail preview looks dark. How can I make it luminous?

I noticed that preview looks well at first launch,  but  after minimizing and unminimizing the window makes previews shady
I need to set all the previews brighter.

**Comment by trappedinspacetime** [comment]
> I noticed that preview looks well at first launch, but after minimizing and unminimizing the window makes previews shady
I need to set all the previews brighter.

I worked around that issue by inserting a  `return` after the line
https://github.com/M7S/dockbarx/blob/pygi-python3/dockbarx/windowbutton.py#L451

**Comment by trappedinspacetime** [comment]
@xuzhen I tried the latest updates. You added live preview for minimized windows, thank you for that.
Unfortunately it won't update frequently. If I wave the pointer over the overview pane it shows the latest preview image from the hidden window. Is it possible to add a loop which is updating the preview image while mouse hover over the preview pane?

**Comment by xuzhen** [comment]
@trappedinspacetime  X server does not allow getting a preview of a minimized window, the preview must be obtained before the window is minimized. The current implementation is to obtain a preview image when the window notifies X server of user action or area change, and display it when the window is minimized.

I tried to get the preview periodically, but the effect is not satisfactory. If there are many windows, the CPU usage will be quite high, and the whole program will be laggy.
