### ISSUE TITLE
Media control icons on top position?

### ISSUE THREAD

**Issue by kmvan** [M7S/dockbarx#155]
![image](https://user-images.githubusercontent.com/3839554/97775952-a3fdc780-1b9f-11eb-8816-e7501dac5947.png)

![image](https://user-images.githubusercontent.com/3839554/97775963-b7a92e00-1b9f-11eb-8307-7deb8f2b17ad.png)

Can I move the control icons to bottom like image2?

**Comment by xuzhen** [comment]
fixed in https://github.com/xuzhen/dockbarx/commit/a3e21862962c23ba1f8bb2cede11cc728f7f4071

**Comment by kmvan** [comment]
Thanks
