### ISSUE TITLE
spotify double icon (lanucher + app)

### ISSUE THREAD

**Issue by neoabs** [M7S/dockbarx#164]
The issue is that launcher does not contain app if it is running. If i launch spotify I have sth like this:

![image](https://user-images.githubusercontent.com/53402602/107504073-1288f300-6b9b-11eb-94b7-fe0df20247b5.png)

 I tried checking with ```xprop|grep WM_CLASS``` but it is not the issue. I can literally start app, unpin launcher, pin app press play and it doubles again. If I remove ```%U``` from launcher command spotify: App is contained in launcher UNTIL I press play. Then icon changes to the one in ```/usr/share/spotify/icons/``` and I have a new app:

before: 
![image](https://user-images.githubusercontent.com/53402602/107504788-19643580-6b9c-11eb-8091-68b7024e2197.png)
after pressing play (I changed default icons):
![image](https://user-images.githubusercontent.com/53402602/107504830-26812480-6b9c-11eb-95bd-a7e0768801aa.png)

It seems to be fault of Spotify (probably changes icon between playing musing and pause). Other idea is that there is a conflict between Audacious and Spotify but this is rather miss.

I am running xubuntu latest stable (focal fosa) but I had the same issue on Manjaro xfce.

**Comment by neoabs** [comment]
Update. I re-added ```%U``` to launcher and it now behaves the same way as without it (app is in launcher group until I press play). So I am pretty sure it is ---press play--- related. Maybe there is some sort of workaround?

**Comment by xuzhen** [comment]
Should be fixed in https://github.com/xuzhen/dockbarx/commit/c5fd81092022209dc40c7d3d6e694c882506e36f. The new packages have been uploaded to [my PPA](https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx)

**Comment by neoabs** [comment]
It works. I just had to re-pin application

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
