### ISSUE TITLE
Dockx allways stays over fullscreen windows in xfce4.18

### ISSUE THREAD

**Issue by Flashwalker** [M7S/dockbarx#171]
After update to xfce4.18 Dockx now allways stays over full-screen windows.

Alsoin  Dockbarx xfce applet there is a glitch with popups (size sometimes become huge; popup not always hiding)

**Comment by xuzhen** [comment]
Fixed in https://github.com/xuzhen/dockbarx/commit/eb586b8f3f02898635224f722d47ad4544226c75
You can set window layer to "default layer" instead of "above other windows" now.

**Comment by Flashwalker** [comment]
Thanks, i'll try to compile it

**Comment by xuzhen** [comment]
And the popup issues should be fixed in https://github.com/xuzhen/xfce4-dockbarx-plugin v0.7.1

**Comment by Flashwalker** [comment]
Thanks, i found update in ppa, much appreciated!
It works fine again with `Type: dock`, and `Behavior: standart` 👍
