### ISSUE TITLE
Dockx 1.0~beta2-1~ppa1: Buttons do not fit into the vertical dock

### ISSUE THREAD

**Issue by Flashwalker** [M7S/dockbarx#172]
Hi  
After update from **0.92-1\~webupd8\~zesty0** to **1.0\~beta2-1\~ppa1** (xuzhen666/dockbarx)  
i encountered a new strange issue with `dockx`.

### Group buttons now do not fit into the dock in vertical layout
 and now i have a triangle buttons at the bottom, wich thumbs through the group buttons:
![image](https://user-images.githubusercontent.com/2188215/210283257-602b767b-6ea4-430d-8ce6-4c2ed1c15703.png)

![image](https://user-images.githubusercontent.com/2188215/210283280-3270d7dc-e7f6-41cf-a413-40c2104d97f9.png)

It's like the group buttons list was croped and got paging buttons.

### And also  the first four buttons have a wider hotspot area than the actual width of the dock
![image](https://user-images.githubusercontent.com/2188215/210283383-fe3c4cc1-9a9b-43e5-821d-ee7a170df54e.png)

### And also if I put the dock on the right side of the screen, the background of the dock shifts to the right:
![image](https://user-images.githubusercontent.com/2188215/210283904-763d53c6-f514-46ea-ac7d-f52cdd7f2f98.png)

### Also one more (the old one) issue:
`dockx` has a 1px gap between the dock and the maximized window.
![image](https://user-images.githubusercontent.com/2188215/210285515-f330c4d4-3dbf-4d1d-ae1e-5ace75f3ff1c.png)
![image](https://user-images.githubusercontent.com/2188215/210285530-be3e7dea-85e1-4da3-b997-1f6f429e7861.png)
(at the last screenshot the background of the dock is not shifted because of the Size set to 72)

### Additional info
All it happens only with the vertical layout of the `dockx`.

Dockbarx xfce panel pluggin is ok.

here is some stdout: https://fars.ee/ZGWz

**Comment by xuzhen** [comment]
The first two problems should be fixed in https://github.com/xuzhen/dockbarx/commit/fd4f6ad06f116d30daed2bb04aa2a8358b9d9654. New packages were already uploaded to the PPA.

The 3rd one may also be fixed in that commit. I'm not sure because I can't reproduce it on my system.

And the 1px gap, it's not a real gap but a translucent shadow effect of the panel. Choosing a bright background color like yellow or red, you will see it.

**Comment by Flashwalker** [comment]
ok, thanks for hot fix :+1:

**Comment by Flashwalker** [comment]
background shift fixed too.
