### ISSUE TITLE
ModuleNotFoundError: No module named 'dockbarx'

### ISSUE THREAD

**Issue by ghost** [M7S/dockbarx#174]
Hello, I tried to install dockbarx and after that it refuse to launch with that error : 

```
Traceback (most recent call last):
  File "/home/<redacted>/anaconda3/bin/dockx", line 20, in <module>
    from dockbarx.log import *
ModuleNotFoundError: No module named 'dockbarx'
```

I use Arch Linux, and tried with both yay, and makepkg.
If there's a need for more informations please let me know

**Comment by xuzhen** [comment]
You installed dockbarx into your anaconda3 environment.

Remove all the anaconda3 related paths from the PATH environment variable and reinstall dockbarx.
```
yay -R dockbarx
export PATH="$(echo "$PATH" | sed 's#[^:]*anaconda3[^:]*:##')"
yay -S dockbarx
```

If you have not remove the make dependencies before, reinstall them as well.

**Comment by xuzhen** [comment]
If you have installed all the dependencies into the anaconda3 environment and don't want to reinstall them, you can edit the dockx file
`sudo sed -i '1s:/usr/bin/python3:/usr/bin/env python3:' ~/anaconda3/bin/dockx`

**Comment by amreo** [comment]
I have solved it with:
```
sudo ln -s /usr/lib/python3.10/site-packages/dockbarx/ /usr/lib/python3.11/site-packages/dockbarx
```
