### ISSUE TITLE
Popup won't pop after button move (drag-n-drop) to another position

### ISSUE THREAD

**Issue by Flashwalker** [M7S/dockbarx#175]
Popup stops to pop if i move any button (drag-n-drop) to another position, until i left-click a once somethere in Dockbarx.
It is something like the mouse-down event is stuck after drag-n-drop

**Comment by xuzhen** [comment]
Fixed in https://github.com/xuzhen/dockbarx/commit/6a925c222c4d6a353e533a066009a76cfb38dc54

**Comment by Flashwalker** [comment]
> Fixed in [xuzhen@6a925c2](https://github.com/xuzhen/dockbarx/commit/6a925c222c4d6a353e533a066009a76cfb38dc54)

Thanx
