### ISSUE TITLE
Collapsed windows in windows list

### ISSUE THREAD

**Issue by Flashwalker** [M7S/dockbarx#177]
I have noticed that if I have several open windows of one application, such as a browser, on the 1st desktop, and they are collapsed (no preview image) in the windows list because there are many of them, 

then another window of that application on the 2nd desktop is collapsed in the windows list too, even it is the only one there.

**Comment by xuzhen** [comment]
Should be fixed in https://github.com/xuzhen/dockbarx/commit/f6d63343801403a8013ad39ae844d210717753b4
