### ISSUE TITLE
Can't pin Wine applications in XFCE4 panel item

### ISSUE THREAD

**Issue by SamHH** [M7S/dockbarx#18]
Specifically, foobar2000. There is no option to pin it and dropping it onto the panel in XFCE4 results in an endless loading cursor state on hover. Otherwise works fine.

0.91.4, Xubuntu 14.04.

Edit: Scratch that, an icon has now appeared (loading cursor state remains). Opening it just results in a small "Error: File not found." dialog.

Edit 2: Eventually caused the panel to crash and have to reload.

**Comment by xuzhen** [comment]
Yes, there is no "Pin application", but you can "Make custom launcher".
And it won't trigger the cursor issue.

**Comment by SamHH** [comment]
Aha, I did get it working. Thank you.

For anyone who stumbles upon this later, it was as easy as setting the command to the path of the file, so for me it was just:

    ~/.wine/drive_c/"Program Files (x86)"/foobar2000/foobar2000.exe
