### ISSUE TITLE
Faulty automatic vertical/horizontal orientation

### ISSUE THREAD

**Issue by docphees** [M7S/dockbarx#19]
The xfce applet often loads as a horizontal bar in a vertical Deskbar mode xfce panel. This leads to small icons that don't fit in the panel. This does happen about one out of ten times on at least three different machines (with very different hardware).
**This regards dockbarx v0.91.4**

I am pretty sure this behavior is related to the exact loading times of the panel.

**I solve this** by entering dockbarx's preferences and simply click "apply". This reloads dockbarx correctly in vertical orientation.

### Proposed Solution:
One way to solve this could be either adding a selection box, defaulting to dockbarx's current automatic behavior, allowing the user to explicitly choose vertical orientation.

**Comment by M7S** [comment]
If this bug still exists it should be posted to the issue tracker of the xfce-plugin.
