### ISSUE TITLE
Please do not remove window previews

### ISSUE THREAD

**Issue by wp9015362** [M7S/dockbarx#2]
Hello,

to answer your question:

> https://plus.google.com/110582468951930692841/posts/5nN98SQAUpt
>
> M7S wrote:
>
> [...] How important is Window previews for DockbarX?
> Would you stop using DockbarX if previews were removed from it?

Please do not remove the window preview feature of DockbarX. It's very important IMHO.

Regards

**Comment by Isakku** [comment]
Thinking the same thing.
