### ISSUE TITLE
New Release ?

### ISSUE THREAD

**Issue by baronleonardo** [M7S/dockbarx#20]
I was wondering if there will be new releases in the future
I see the activity on this fantastic doc has been stopped for 11 months
I hope that this project still alive

**Comment by TiZ-EX1** [comment]
Hey man, just pinging this issue. I upgraded to Xenial today, and grabbed DBX from Wily because no repos have DBX for Xenial yet. Being a release-day adopter sucks when you have PPAs, heh. You might want to make a release to formally fix the tostring -> tobytes thing.

**Comment by xuzhen** [comment]
@TiZ-EX1 try my ppa: https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx

**Comment by M7S** [comment]
New release is made. Sorry for being such a lazy developer.

**Comment by TiZ-EX1** [comment]
Don't sweat it dude. You're still aces in my book. ^.^
