### ISSUE TITLE
"Ignore windows on other monitors" doesn't work

### ISSUE THREAD

**Issue by Giroom** [M7S/dockbarx#23]
Enabling the option turns the launcher/window-switchers into just launchers.

**Comment by xuzhen** [comment]
Are you using the latest code from this repository?
Is there any error messages in terminal?

**Comment by Giroom** [comment]
I'm using the version from the PPA on Linux Mint 17.2 Xfce. How do I get get messages from dockbarx in the terminal? Sorry, I'm still a noob at this.

**Comment by xuzhen** [comment]
The code in official PPA is a bit outdated. You should download the newest codes and replace the old ones.
```
sudo wget https://raw.githubusercontent.com/M7S/dockbarx/master/dockbarx/groupbutton.py -O /usr/share/pyshared/dockbarx/groupbutton.py
sudo wget https://raw.githubusercontent.com/M7S/dockbarx/master/dockbarx/windowbutton.py -O /usr/share/pyshared/dockbarx/windowbutton.py
```

**Comment by Giroom** [comment]
Thank you so much, that made it work perfectly!
