### ISSUE TITLE
Update repo for ubuntu 16.04

### ISSUE THREAD

**Issue by arijitlaik** [M7S/dockbarx#25]
Hi there,
Ubuntu 16.04 packages are not in the repository, hoping you will soon be kind enough to update the packages.
Thanking you in advance :+1:

**Comment by xuzhen** [comment]
The offical PPA has not been updated for a long time, you can try [my PPA](https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx) instead.

**Comment by finalgamer** [comment]
@xuzhen Do you also provide the xfce4 plugin?

**Comment by hotice** [comment]
The official DockBarX PPA wasn't updated for Xenial because it didn't work in Xenial :) I'll update it soon.

**Comment by arijitlaik** [comment]
Thanks Andrew

**Comment by hotice** [comment]
Done, PPA updated (includes the Xfce panel plugin).

**Comment by arijitlaik** [comment]
Since the webupd8 repo has been updated I am closing this issue thanks again for the work :)

**Comment by hotice** [comment]
Not only the WebUpd8 repository but also the DockBarX repo ;)

**Comment by arijitlaik** [comment]
Yup I saw that, a while ago. my bad!
