### ISSUE TITLE
Dock Applets don't work

### ISSUE THREAD

**Issue by hotice** [M7S/dockbarx#26]
Dock Applets don't work at all. Tested in Ubuntu 16.04 and 14.04 with both the latest DockBarX 0.92 and 0.91.4. 

All the applets I enable are reset when I close and reopen the DOckBarX preferences. There's no terminal output to indicate anything related to this.

**Comment by hotice** [comment]
Well, this is weird. I got them to work. Basically, after some dock applets are enabled, you need to click the "refresh" button in the middle of the DockBarX Dock Applets preferences window or else they are not saved.

**Comment by kq01526** [comment]
@hotice :

Have you tested this with DockBarX or with DockX?

DockBarX = Panel applet
DockX = Stand-alone version of DockBarX

Regards
