### ISSUE TITLE
Does dockx support dual monitors?

### ISSUE THREAD

**Issue by assumptionsoup** [M7S/dockbarx#30]
I can only to get dockx to run on one screen.  Even when I set a different primary monitor, dockbarx stubbornly stays on the original.  Restarting dockx doesn't help.

**Comment by W4RH4WK** [comment]
Bump, I am playing around with a dual screen setup and cannot move Dockbarx to my primary monitor.

**Comment by Benguin** [comment]
I couldn't quite get it to work with multiples either. I workaround might be to install devilspie2, a program that searches open windows based on a rule you give it, and can perform actions like "move this window to this position on screen" (including moving it to the correct screen).

**Comment by M7S** [comment]
Sorry for not responing right away. The monitor can be set from commandline:

dockx --monitor 2

**Comment by nicman23** [comment]
using that on mate the dock does not work as a panel (other maximised windows overlap).

A hacky workaround I have done is to have a transparent mate-panel with the same pixel width and ghost it with compiz 0.8.12

**Comment by z** [comment]
@M7S that didn't work for me.

```
% dockx --monitor 2
DockbarX 0.92
DockbarX init
DockbarX reload
/usr/bin/dockx:1211: GtkWarning: IA__gdk_screen_get_monitor_geometry: assertion 'monitor_num < screen_x11->n_monitors' failed
  return screen.get_monitor_geometry(self.monitor)
/usr/bin/dockx:781: GtkWarning: IA__gdk_screen_get_monitor_geometry: assertion 'monitor_num < screen_x11->n_monitors' failed
  mx, my, mw, mh = s.get_monitor_geometry(self.monitor)
```

```
% dpkg -s libgtk2.0-0|grep '^Version' 
Version: 2.24.30-1ubuntu1.16.04.2
```

`dockx` without any flags does give me one dock, and XFCE plugin works, but only in a single panel.

**Comment by anggerbagus** [comment]
try with `--monitor 1` for your extended monitor
and `--monitor 0` or without any flags for your primary monitor

you should not run it from terminal after log in because dockx will be the child of the terminal. so if terminal was closed, so do the dock.
make use a startup script instead. put `dockx --monitor 0 &; sleep 5; dockx --monitor 1;` in your script.

**Comment by z** [comment]
@anggerbagus, thanks this worked, but I think perhaps it's revealed an unsupported feature.  I can't figure out if it's possible to show windows that only exist on the same monitor as the respective dock.  Any idea?

**Comment by JSchoreels** [comment]
@nicman23 , I have fixed the overlap issue in my fork : https://github.com/jschoreels/dockbarx/

I have opened a PR to discuss why the strut is voluntary removed.
