### ISSUE TITLE
AttributeError: 'gnome.applet.Applet' object has no attribute 'readd_container'

### ISSUE THREAD

**Issue by Zenitur** [M7S/dockbarx#38]
Dockbarx 0.91.4
GNOME 2.28

In the first start, DockbarX is working fine. I have been added it in gnome-panel. When I change settings and apply it, DockbarX is dissapperaing. After relogin, it is not appears. I need to clear ~/.gconf/apps/dockbarx to make it working again.

~/.dockbarx/dockbarx.log

`INFO	| 2017-02-07 21:19:15,295	| DockbarX 0.91.4`
`INFO	| 2017-02-07 21:19:15,295	| DockbarX init`
`INFO	| 2017-02-07 21:19:15,445	| DockbarX reload`
`INFO	| 2017-02-07 21:21:45,319	| DockbarX reload`
`ERROR	| 2017-02-07 21:21:45,373	| Traceback (most recent call last):`
`ERROR	| 2017-02-07 21:21:45,374	|   File "/usr/lib64/python2.6/site-packages/dockbarx/dockbar.py", line 779, in __on_theme_changed`
`ERROR	| 2017-02-07 21:21:45,387	|     `
`ERROR	| 2017-02-07 21:21:45,388	|   File "/usr/lib64/python2.6/site-packages/dockbarx/dockbar.py", line 641, in reload`
`ERROR	| 2017-02-07 21:21:45,388	|     `
`ERROR	| 2017-02-07 21:21:45,388	| AttributeError: 'gnome.applet.Applet' object has no attribute 'readd_container'`
`ERROR	| 2017-02-07 21:21:45,424	| Traceback (most recent call last):`
`ERROR	| 2017-02-07 21:21:45,425	|   File "/usr/lib64/python2.6/site-packages/dockbarx/theme.py", line 145, in on_theme_changed`
`ERROR	| 2017-02-07 21:21:45,431	|     `
`ERROR	| 2017-02-07 21:21:45,432	|   File "/usr/lib64/python2.6/site-packages/dockbarx/theme.py", line 204, in reload`
`ERROR	| 2017-02-07 21:21:45,432	|     `
`ERROR	| 2017-02-07 21:21:45,432	|   File "/usr/lib64/python2.6/site-packages/dockbarx/theme.py", line 301, in load_surface`
`ERROR	| 2017-02-07 21:21:45,432	|     f.close()`
`ERROR	| 2017-02-07 21:21:45,432	| MemoryError`

**Comment by M7S** [comment]
GNOME 2.28? It seems like you renew your system as frequently as I answer bug reports...

Apparently I have managed to break DockbarX as GNOME applet while working on DockX or DockbarX as a AWN applet. I commited fix for this bug. Sorry it took this long for me to look at it.

**Comment by Zenitur** [comment]
Yes, I still use GNOME2 cause by GNOME3 is unusable, and Unity DE isn't available in my Linux distribution. Thank you for a fix! I'll test in few days...
