### ISSUE TITLE
On latest DockX, minimizing

### ISSUE THREAD

**Issue by ghost** [M7S/dockbarx#4]
With the latest updates for dockbarX/dockbarX xfce plugin ( I see it with both), I see the following behaviors:

Minimizing a window of a pinned app makes all mouse actions unresponsive. I have seen this with terminal emulator, file manager, skype, chrome
Right clicking on the applet and choosing Refresh makes the icon group of any app with a minimized window disappear. They only reappear if I unminimize all windows of the app and refresh the plugin again.

Snippet of crash (I have the complete crash if needed) follows:
PythonArgs: ['/usr/share/xfce4/panel/plugins/xfce4-dockbarx-plug', '-s', '41943065', '-c', '/home/mikec/.config/xfce4/panel/dockbarx-15.rc']
Traceback:
Traceback (most recent call last):
File "/usr/lib/pymodules/python2.7/dockbarx/windowbutton.py", line 154, in __on_window_state_changed
self.group_r().button.update_state_if_shown()
File "/usr/lib/pymodules/python2.7/dockbarx/groupbutton.py", line 1518, in update_state_if_shown
self.update_state()
File "/usr/lib/pymodules/python2.7/dockbarx/groupbutton.py", line 1503, in update_state
surface = self.icon_factory.surface_update(state_type)
File "/usr/lib/pymodules/python2.7/dockbarx/iconfactory.py", line 163, in surface_update
surface = f(surface, *_args)
File "/usr/lib/pymodules/python2.7/dockbarx/iconfactory.py", line 409, in __command_if
surface = f(surface, *_args)
File "/usr/lib/pymodules/python2.7/dockbarx/iconfactory.py", line 715, in __command_transp_sat
new = cairo.ImageSurface(cairo.FORMAT_ARGB32, w, h)
UnboundLocalError: local variable 'w' referenced before assignment
UserGroups: adm cdrom dip lpadmin plugdev sambashare sudo
_LogindSession: /user/1000.user/c2.session
ApportVersion: 2.14.1-0ubuntu3.2
Architecture: amd64
Dependencies:
acl 2.2.52-1
adduser 3.113+nmu3ubuntu3
apt-utils 1.0.1ubuntu2.1
at-spi2-core 2.10.2.is.2.10.1-0ubuntu1
base-passwd 3.5.33
busybox-initramfs 1:1.21.0-1ubuntu1
colord 1.0.6-1
coreutils 8.21-1ubuntu5
cpio 2.11+dfsg-1ubuntu1
dbus 1.6.18-0ubuntu4
dbus-x11 1.6.18-0ubuntu4
dconf-gsettings-backend 0.20.0-1
dconf-service 0.20.0-1
debconf 1.5.51ubuntu2
debconf-i18n 1.5.51ubuntu2
debianutils 4.4
dockbarx 0.91.3-1~webupd8~trusty0 [origin: LP-PPA-dockbar-main]
dockbarx-applet-appindicator 0.91.3-1~webupd8~trusty0 [origin: LP-PPA-dockbar-main]
dockbarx-applet-battery-status 0.91.3-1~webupd8~trusty0 [origin: LP-PPA-dockbar-main]
dockbarx-applet-clock 0.91.3-1~webupd8~trusty0 [origin: LP-PPA-dockbar-main]
dockbarx-applet-namebar 0.91.3-1~webupd8~trusty0 [origin: LP-PPA-dockbar-main]
dockbarx-applet-volume-control 0.91.3-1~webupd8~trusty0 [origin: LP-PPA-dockbar-main]
dockbarx-common 0.91.3-1~webupd8~trusty0 [origin: LP-PPA-dockbar-main]
dockbarx-dockx 0.91.3-1~webupd8~trusty0 [origin: LP-PPA-dockbar-main]

**Comment by sergioad** [comment]
After 7 years this issue persists in Manjaro friends
![Uploading Captura de pantalla_2021-03-08_00-06-35.png…]()

**Comment by sergioad** [comment]
After 7 years this issue persists in Manjaro friends

**Comment by xuzhen** [comment]
@sergioad Your screenshot was not uploaded. And the bug described by OP has already been fixed long ago.
