### ISSUE TITLE
Port Dockbarx and Dockbarx plugin to ARM7

### ISSUE THREAD

**Issue by coreybruce** [M7S/dockbarx#41]
Hi I am using Xubuntu 16.04LTS on my raspberry pi 3 and love if you added a arm version to your ubuntu PPA!

**Comment by xuzhen** [comment]
try my PPA: https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx

**Comment by gameslayer** [comment]
@xuzhen does that include the xfce dockbarx plugin?

**Comment by xuzhen** [comment]
Sorry, now added.

**Comment by gameslayer** [comment]
Thank you very much, I hope this will continue to be updated :D

**Comment by coreybruce** [comment]
I don't think there repo has been updated to 18.04 yet
