### ISSUE TITLE
Dockx battery applet not working archlinux

### ISSUE THREAD

**Issue by Techman35** [M7S/dockbarx#42]
Dockx battery applet is not working on Archlinux
![screenshot5](https://cloud.githubusercontent.com/assets/14001966/26201410/4f2c339c-3bc2-11e7-8441-df3727e1e92a.png)

**Comment by xuzhen** [comment]
It is designed for GNOME 2 back in 2010. Too many things have changed since then.
I am trying to revive it for the current desktop environment

**Comment by Techman35** [comment]
> It is designed for GNOME 2 back in 2010. Too many things have changed since then.
> I am trying to revive it for the current desktop environment

Thanks, please is the only plugin that is stopping me from using dockbarx as stand alone panel
thanks for you reply and waiting for the working plugin. :)

**Comment by xuzhen** [comment]
The reforged battery applet has already been in the [pygi-python3 branch](https://github.com/M7S/dockbarx/tree/pygi-python3)
