### ISSUE TITLE
XFCE4 Plugin not working.

### ISSUE THREAD

**Issue by josehfurtado** [M7S/dockbarx#46]
"Blend with panel" doesnt show anything. How to fix?

**Comment by itsjef** [comment]
This might be an xfce4 plugin issue rather than DockbarX's

https://github.com/TiZ-EX1/xfce4-dockbarx-plugin/issues/26

**Comment by anggerbagus** [comment]
Or if you put it in "panel 0", it will works with "Blend with panel"

**Comment by josehfurtado** [comment]
Solid color work well but I don't want to care about panel color. XFCE auto set this. But it's solved. Before set dockbarx in panel zero, installing last version, blend function working now. Thank you guys.

**Comment by nkkollaw** [comment]
Same here. Is there anything that actually fixes the problem?

**Comment by M7S** [comment]
There's a better chance to get the question answered over at TiZ-EX1/xfce4-dockbarx-plugin.

**Comment by josehfurtado** [comment]
Sure, this is about plug in, a old version. Install latest version [https://github.com/TiZ-EX1/xfce4-dockbarx-plugin](url) of the plug in, in my case, XUbuntu Xenial. Them...

> ./waf configure && ./waf build && sudo ./waf checkinstall

should fix blend function in XFCE.
