### ISSUE TITLE
Icons in Dockbarx disappear after changing workspace 

### ISSUE THREAD

**Issue by KabbAmine** [M7S/dockbarx#5]
I've got a lot of strange behavior with the last dockbarx versions.

I'm using Xubuntu 14.04, with dockbarx 0.91.4 as a xfce-plugin, and the problem is when I change workspace and come back to the previous one where I have opened programs, the dockbarx icons disappear (In the dock and the plugin), so I should update dockbarx to get them back.

*N.B: Sorry for my poor English.*

**Comment by JanFrydrych** [comment]
I have the same problem. Unfortunately I don't know how to install Xuzhen fork, or how to modify broken files. I would be grateful for any help.

**Comment by KabbAmine** [comment]
@JanFrydrych Just download [Xuzhen's fork](https://github.com/xuzhen/dockbarx) and follow the [instructions of a manual installation](https://github.com/xuzhen/dockbarx#manual-installation).

**Comment by JanFrydrych** [comment]
Thank you very much KabbAmine. Should I uninstall the previous version of Dockbarx before installing fork? 
Isn't Dockbarx developed any more?

**Comment by KabbAmine** [comment]
Yeah, better to uninstall it before.

> Isn't Dockbarx developed any more?

Maybe, the last commit in the official repository was done a few months ago.
Use and follow the fork above, it works as expected and Xuzhen usually answers quickly.

**Comment by xuzhen** [comment]
@JanFrydrych If you are using ubuntu, you can use [this PPA](https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx). It contains all the patches after 0.91.4 release. Other debian-based distributions may also be compatible.

**Comment by JanFrydrych** [comment]
Hi,
After the update to 16.04 dockbarx xfce panel plugin doesn’t work. I had tried to reinstall Xuzhen fork but it didn’t help.

**Comment by M7S** [comment]
xuzhen fix is used.
