### ISSUE TITLE
Switching to app shouldn't open minimized windows

### ISSUE THREAD

**Issue by nkkollaw** [M7S/dockbarx#51]
If I have some windows minimized for a certain app and I switch to it by clicking its icon in the dock, all minimized windows get un-minimized and open with the other ones.

Minimized windows should stay minimized/be ignored when one switches apps.

**Comment by M7S** [comment]
I'm not sure what behavior is better, this or the current one. I could always make that an option. (Since we are drowning in options already one more probably wouldn't be the end of the world.) But what should be the default?

Can you give a use case where this behavior is better?

**Comment by nkkollaw** [comment]
I would think the use case in any time you have a software where you work on multiple files at the same time but only one at once. For instance, I use windows heavily to group browser tabs while programming, minimize the ones I don't need at the moment, and switch back and forth between the HTML editor and the browser window I need. Then during break I open my "tabs group" with personal sites like Reddit and HN, etc. etc.

I think the default should be that minimized windows stay minimized, since that's what the user is attempting to do: keep some windows minimized.

**Comment by M7S** [comment]
I finally got around to do something about this one. I didn't make it an option (for now) but simply changed the behavior. Let's see if anyone complains about the change.
