### ISSUE TITLE
Select window on hover

### ISSUE THREAD

**Issue by benburrill** [M7S/dockbarx#56]
I would like windows to be selected on hover rather than on click, making it easier to find the window I want.

This would serve a similar purpose to opacify I think, but it would work without compiz and be more what I want anyway.

**Comment by M7S** [comment]
This sounds a bit messy to me since all windows will be brought up and left unordered but I made a branch to test it anyway. Try it and see if does what you want.

https://github.com/M7S/dockbarx/tree/hoverselect

**Comment by benburrill** [comment]
I was thinking more like [this](https://github.com/benburrill/dockbarx/tree/hoverselect).  However there are some problems with it.  The `reorder_window_list` gconf setting needs to be disabled for it to be even slightly useful, and then you have to change the left mouse click action so that when you click on it it doesn't minimize the window.  There are a few problems with focus too which I didn't bother with.  

I also left the delay super long in that commit for testing purposes.
