### ISSUE TITLE
Build for 17.10

### ISSUE THREAD

**Issue by philthynz** [M7S/dockbarx#57]
Would be awesome if we can use this in 17.10 please

**Comment by M7S** [comment]
Oh. I didn't even know it wasn't packaged for 17.10. I wonder if there is any problem with running it on 17.10 that I'm not aware of (still using 16.04) or if @hotice simply (and understandably) thinks DockbarX is dead and has stopped packaging it.

**Comment by xuzhen** [comment]
You could try my ppa: https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx

**Comment by phillip-white-sociomantic** [comment]
@xuzhen Thanks i'll give it a try

**Comment by philthynz** [comment]
Thanks i'll give it a try

**Comment by nkkollaw** [comment]
I installed the Xenial version on Bionic and didn't notice any problems...

**Comment by M7S** [comment]
OK, so @hotice seems to have disappeared from Internet. (I hope he is OK :( .) So there are nobody mantaining DockbarX ppa at the moment.

**Comment by nkkollaw** [comment]
Shit.

**Comment by Lesik** [comment]
I mean, he was [active in August this year](https://github.com/gnunn1/tilix/issues/1496).
