### ISSUE TITLE
Is possible to make dockbarx auto refresh?

### ISSUE THREAD

**Issue by elfarqy** [M7S/dockbarx#65]
i'm using ubuntu 16.04, xfce4-panel 4.12.0 (Xfce 4.12)

When open a new window, icon not appeared in panel. Icon will appear after right clicking in panel and click refresh. 
![attached images](https://user-images.githubusercontent.com/5682478/38286378-4c625310-37ef-11e8-89be-019e9542309d.png)

**Comment by M7S** [comment]
Can you post the log (~/.dockbarx/log/dockbarx.log) so that we can see if there is some error causing this behavior?

**Comment by xuzhen** [comment]
Could try [my fork](https://github.com/xuzhen/dockbarx/) or [my PPA](https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx/+packages)? I've committed a patch, it may fix this issue.
