### ISSUE TITLE
All paths are hard-coded

### ISSUE THREAD

**Issue by TiZ-EX1** [M7S/dockbarx#69]
So I'd like to be able to make a self-contained installation of DBX inside a virtualenv that I can carry around with me between distros. This seemed like it was working pretty well with quodlibet, but I couldn't do it with DBX because all the paths in setup.py--and maybe other parts of the codebase--are hard-coded to /usr/share.

Can you do anything to make this configurable? I've gotta look into this for my own stuff, too.

**Comment by nkkollaw** [comment]
Would symlinks work..?

**Comment by TiZ-EX1** [comment]
No, not remotely. If you have to make symlinks into /usr, depending on how many there are, that may defeat the entire purpose. Manually installed--as opposed to the package manager--applications are supposed to go in /usr/local anyways, and above all, you are supposed to at least be able to define the installation prefix. It looks like DBX's setup.py tries to throw *a whole lot* of stuff into /usr and has hardcoded that assumption. I haven't yet tried just copying all the files into a python2.7 virtualenv myself but I'll probably do that later.

**Comment by M7S** [comment]
Perhaps it was a mistake to install dockbarx as a system wide python module (or whatever the correct terminology is) with distutils.core. It's not like a lot of other python applications will ever want to use "import dockbarx". And there's also no easy way to uninstall with this system.

Perhaps it's time to make a new install script. How does other programs written in python do it?

**Comment by alxpettit** [comment]
@M7S I believe the de facto standard way to do it _is_ with `setuptools`, and with `from pkg_resources import load_entry_point` in a python script under `/usr/bin/` or `/usr/local/bin/` that's pulling from something like `/usr/.../site-packages`. I've never seen an example of a large Python project that _wasn't_ installed that way, except dockbarx which seems to have its core code straight under the binary directory? Deluge, youtube-dl, wikicurses -- almost everything on my machine is found under site-packages and pulled from a script in a bin dir. (This includes packages not installed via pip)

For example, take a look at [youtube-dl's setup.py](https://github.com/rg3/youtube-dl/blob/master/setup.py). They seem to prefer `setuptools` and use `distutils`as a fallback if it's not available.

**Comment by alxpettit** [comment]
Hmm. I checked out `youtube-dl`, and they have a build system that's... really involved. It provides ways of compiling to a .exe file on Windows, compiling to a Linux binary file on Linux, compiling to a .exe for Windows from Linux...

But if you run `python3 ./setup.py build`, it seems happy to simply plop the `site-packages` files under `./build`. So making it work portably with their system seems totally possible without using their fancy pantsy py2exe stuff.

**Comment by M7S** [comment]
I've removed all the hard-coded paths now except for "glib-compile-schemas /usr/share/glib-2.0/schemas". I'm not sure what to do with that one.

**Comment by M7S** [comment]
Hopefully everything is in order now.
