### ISSUE TITLE
Wine apps displaying wrong icons

### ISSUE THREAD

**Issue by thecrazy** [M7S/dockbarx#7]
Hi,

I have some wine applications that don't display the proper icon, instead of the icon configured in the launcher I get the default wine icon.

For example, vsphere client 5 starts up with the proper icon but once you log in it reverts to the default wine icon. I have tested this with the regular XFCE taskbar and this doesnt happen.

**Comment by rauldipeas** [comment]
Same bug here.

**Comment by M7S** [comment]
The patch in #52 probably fixed this.
