### ISSUE TITLE
dockbarx & libreoffice 6

### ISSUE THREAD

**Issue by Laurencio** [M7S/dockbarx#70]
Hello.  
I find that docbarx does not work right with libreoffice 6.
I don't know if it is a problem of docbarx or libreoffice (probably libreoffice) but if anyone know a workaround i would appreciate. 
wrong icon behaviour.
I've tried it on linuxmint, mx-17 and antergos.

**Comment by Laurencio** [comment]
Some days ago: https://bugs.launchpad.net/dockbar/+bug/1764868:

"Using dockbarx 0.93 and xfce4-dockbarx-plugin on mx-linux 17.

When launching an application of libreoffice 6.x (calc, writer, etc) dockbarx shows a the generic white libreoffice icon. No option to pin app.
Expected behavior: show the application icon and let it pin.

If libreoffice (generic) is launched a writer icon is shown. Now it let it to be pinned. If you use that icon again, it launches writer, but another equal icon is shown. No option to pin this.

So, the general behaviour is wrong.

With libreoffice 5.x it works fine.

Tried also on linuxmint 18.3. (Dockbarx installed from the GitHub and also from the webupd8 ppa) Same happens. It works fine with libreoffice 5.x and is wrong with libreoffice 6."

Similar experience testing today: https://forum.xfce.org/viewtopic.php?id=12195

**Comment by M7S** [comment]
I can confirm this behavoir. I think it's because libreoffice 6 has the wrong class name when it starts. It is changed after a while. I tried to fix this a while back by having wnck to report when a class name changes, and it does report that the name _has changed_ but wnck still only gives the old class name, so I don't know if there's a simple way to fix this.

**Comment by xuzhen** [comment]
It turned out that LO 6.x changed its default window class.
Here is a patch.
```
--- dockbar.py	2018-05-10 19:47:53.826824275 +0800
+++ dockbar.py	2018-05-10 19:48:45.104024085 +0800
@@ -943,6 +943,7 @@
            self.globals.settings["separate_prism_apps"]:
             identifier = self.__get_prism_app_name(window)
         elif identifier.startswith("openoffice.org") or \
+           identifier.startswith("soffice") or \
            identifier.startswith("libreoffice"):
             identifier = self.__get_ooo_app_name(window)
             if self.globals.settings["separate_ooo_apps"]:
@@ -1079,6 +1080,8 @@
         resclass = window.get_class_group().get_res_class().lower()
         if "libreoffice" in resclass:
             office = "libreoffice"
+        elif "soffice" in resclass:
+            office = "libreoffice"
         elif "openoffice.org" in resclass:
             office = "openoffice.org"
         if not self.globals.settings["separate_ooo_apps"]:
```

**Comment by xuzhen** [comment]
OpenOffice 3+ has same issue. A new patch here
```
--- dockbar.py	2018-05-10 19:47:53.826824275 +0800
+++ dockbar.py	2018-05-11 00:53:49.832440170 +0800
@@ -942,7 +942,8 @@
         if identifier == "prism" and \
            self.globals.settings["separate_prism_apps"]:
             identifier = self.__get_prism_app_name(window)
-        elif identifier.startswith("openoffice.org") or \
+        elif identifier.startswith("openoffice") or \
+           identifier.startswith("soffice") or \
            identifier.startswith("libreoffice"):
             identifier = self.__get_ooo_app_name(window)
             if self.globals.settings["separate_ooo_apps"]:
@@ -1079,6 +1080,12 @@
         resclass = window.get_class_group().get_res_class().lower()
         if "libreoffice" in resclass:
             office = "libreoffice"
+        elif "soffice" in resclass:
+            office = "libreoffice"
+        elif "openoffice " in resclass:
+            office = "openoffice" + resclass.split(" ")[1][0]
+        elif "openoffice.org 3" in resclass:
+            office = "openoffice.org3"
         elif "openoffice.org" in resclass:
             office = "openoffice.org"
         if not self.globals.settings["separate_ooo_apps"]:
```

**Comment by Laurencio** [comment]
Great!
I could use the patch on mx-17. Dockbarx 92 from Debian Testing repo.
It works.
Thank you.
