### ISSUE TITLE
Spotify logo 

### ISSUE THREAD

**Issue by jccall80** [M7S/dockbarx#72]
Spotify Logo doesn't work. Just check the next image to see what is doing:

https://i.imgur.com/VDWGiLQ.png

Has no icon. This doesn't always happen. When happens you close and open it again and then works. 

Strange... Sometimes do it... sometimes not.

**Comment by M7S** [comment]
Spotify starts with wrong class name. It changes after a second or so but then wnck has already sent the wrong name to dockbarx and dockbarx is unable to recognise it properly. wnck should be able to tell when a class name changes but that doesn't seem to work as it should. So I don't know how to fix this.

**Comment by Lesik** [comment]
@jccall80 Do you observe this behavior with other Electron-based apps like Slack, VSCode or Skype?

**Comment by xuzhen** [comment]
It may be already fixed with https://github.com/M7S/dockbarx/issues/78
