### ISSUE TITLE
Error 404: Not Found

### ISSUE THREAD

**Issue by MarkyMarkz** [M7S/dockbarx#73]
Hello,
I tried to install dockbarx with `sudo add-apt-repository ppa:dockbar-main/ppa` but all I get is 
```
HTTP Error 404: Not Found
Cannot add PPA: ''This PPA does not support bionic''.
```
Could someone please tell me what I missed.
Thank you in advance!

**Comment by jccall80** [comment]
Message is quite clear... The ppa that you use doesn't cotnain packets for ubuntu bionic. Latest version is Zesty

**Comment by MarkyMarkz** [comment]
Thanks again.
