### ISSUE TITLE
Some applications don't appear in the dock until you refresh it.

### ISSUE THREAD

**Issue by Alexmitter** [M7S/dockbarx#82]
For example this is appearing with the popular Minetest game.
It only appears after doing a refresh. Maybe something like a automatic refresh all 10 seconds would help if it is really not possible to detect the new process when started.

Sorry i did not see #65 is already referring to that issue.

**Comment by xuzhen** [comment]
Should be fixed now. Try [my fork](https://github.com/xuzhen/dockbarx/) or [my PPA](https://launchpad.net/~xuzhen666/+archive/ubuntu/dockbarx/+packages)

**Comment by Alexmitter** [comment]
@xuzhen can confirm it is fixed.
