### ISSUE TITLE
How to use `Recent/Most used/Related` items in xfce?

### ISSUE THREAD

**Issue by kmvan** [M7S/dockbarx#83]
![image](https://user-images.githubusercontent.com/3839554/47367637-a86e8a80-d712-11e8-85d6-f86851154647.png)

They have empty sub item, any idea to use?

**Comment by mfschumann** [comment]
For me (Manjaro Linux with xfce 4.12) installing zeitgeist fixed it.

**Comment by kmvan** [comment]
zeitgeist I installed, but nothing to show?

**Comment by M7S** [comment]
I don't think recent menu works for thunar (as in your screenshot) try with something like libreoffice writer or gimp.

**Comment by kmvan** [comment]
Okey. Anyway thanks.
