### ISSUE TITLE
Backup and restore all dockbarx preferences.

### ISSUE THREAD

**Issue by RnDevelover** [M7S/dockbarx#84]
I could not find a way to backup and restore all preferences to move my settings to another linux setup.

**Comment by xuzhen** [comment]
backup: ```gconftool --dump /apps/dockbarx > dockbarx.xml```
restore: ```gconftool --load dockbarx.xml```
and don't forget ~/.dockbarx

**Comment by M7S** [comment]
Added to the FAQ in README.
