### ISSUE TITLE
Click the dockbarx windowlist if xfce-panel autohide

### ISSUE THREAD

**Issue by xorgx3** [M7S/dockbarx#9]
Hi,
Now If i have a two or more window on docbarx windowslit and auto hide panel i can't for example clicking on interest window, because panel is hidden and click do nothing. 
Is possible to change dockbar to "kept" panel not hidden while I don't click some option? Whiskermenu works in this way. I hope you know what I mean.

**Comment by anggerbagus** [comment]
you must be fast! :wink: 
maybe it's [xfce-plugin](https://github.com/TiZ-EX1/xfce4-dockbarx-plugin/) issues. It doesn't happen if dockx not used in panel.
