### ISSUE TITLE
No Way To Disable Window List

### ISSUE THREAD

**Issue by ghost** [M7S/dockbarx#90]
Hey so I've been happily using DockbarX (specifically xfce-dockbarx-plugin) for a long long time and I've figured out that on XFCE through Compiz I can set it up so when I click on an item within the dock that has multiple windows open I can get an animated full screen preview of both applications. This is really handy and super cool, but the window list also pops up. 

Would it be possible to add a check box within the settings to disable the window list please?

**Comment by ghost** [comment]
or alternatively, is there a way I can disable that functionality manually that I'm missing?

**Comment by M7S** [comment]
The window list isn't supposed to pop up when using compiz scale. I commited a posible fix for this bug.
