### ISSUE TITLE
Is this project still active ?

### ISSUE THREAD

**Issue by baronleonardo** [M7S/dockbarx#94]
DockbarX still depends on python2 at some stages .. and python2 will reach it's life-end at January 2020
https://pythonclock.org/
so any plans for that ?

**Comment by brunoais** [comment]
The project is alive but the owner doesn't have time to develop it as he used to.
You may just apply that update yourself, if you want to.
python's 2to3 tool should make most work just fine.

**Comment by Jeremi360** [comment]
Someone in Arch commuity made working gtk3 port that works as mate applet:
https://aur.archlinux.org/packages/dockbarx-gtk3-git/ :smile:

**Comment by M7S** [comment]
I'm working at a python3 port. 2to3 did most of the work but there's a few bugs to fix before I can commit anything. It's only possible to port the gtk3 version though, since there's no pygtk library in python3.

**Comment by M7S** [comment]
Feel free to try out the [python3/gtk3 port](https://github.com/M7S/dockbarx/tree/pygi-python3) and report any bugs.
